name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Gradle
        run: "./gradlew build"
      - name: Publish with Gradle
        if: ${{ forgejo.event_name != 'pull_request' && forgejo.ref == 'refs/heads/staging' }}
        run: "./gradlew publish -PpubUrl=${{secrets.MAVEN_REPO}} -PpubUsername=${{secrets.MAVEN_USER}} -PpubPassword=${{secrets.MAVEN_PASSWORD}}"
